# This workflow will build a package using Maven and then publish it to Sonatype.
name: Maven Deploy

# Run workflow on commits to the `master` branch
on:
  push:
    branches:
      - release/**

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.PGP_KEY }}
          gpg_passphrase: ${{ secrets.PGP_PASSPHRASE }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}